### ISSUE TITLE
spec-0.2.1

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#104]
Creating new specifications with some fixes like removing some things from the context (issue #102) and fixing various typos (using `miff` instead of `mmif`, wrong spellings of tools, using 0.1.0 instead of 0.2.0, forgetting `vocabulary` as part of a path.

Most other changes on the branch are patch-level changes. 

However, there is one problem with commit  https://github.com/clamsproject/mmif/commit/818aebb6e38253117580f2dd240f171b31fc8b2e in that it is changing files in `docs/0.1.0` and `docs/0.2.0`, and those are specification documents that have already been published under those version numbers and we do not want to change them the next time we merge into master. @angus-lherrou, was there any specific reason to do this? If not we should roll back those changes.

**Comment by angus-lherrou** [comment]
Nope that was an accident, I'll roll back those changes.

**Comment by marcverhagen** [comment]
Don't make it a huge priority if this is a lot of work. Looking at what the actual differences are it isn't a big deal, especially given that those were just 0.1.0 and 0.2.0 versions.

**Comment by keighrim** [comment]
#106 fixes this.
