### ISSUE TITLE
add versions in the nav-bar of the mmif website

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#110]
Add a dropdown style menu item to the top navigation bar to jump between old versions.

**Comment by keighrim** [comment]
Although #109 is merged, I think we can include a few more commits addressing this issue before we tag `spec-0.2.1` on the master branch.

**Comment by keighrim** [comment]
#111 addresses this issue, and that makes 9e960e078f27f55f0fa0f2a301a3561da1d53ccd to be ready to be tagged as `spec-0.2.1`. @marcverhagen would you like to tag?

**Comment by marcverhagen** [comment]
@keighrim I tagged that commit. It looks good.
