### ISSUE TITLE
The future of this repo

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#112]
We are considering splitting this repository into a specifications and an SDK repository. Separately we are considering doing away with the separate versioning numbers.

Things we do not like about the current versioning scheme:

1. It is hard to explain.
2. The major and minor versions of spec and py track each other, but the patch level doesn't.
3. Creating a new commit on a spec branch tends to break tests, merging a branch with those errors into master does not seem very nice.

If versions go in lockstep we will be faced with many published versions of the specifications at mmif.clams.ai that are identical. This is because updates to the SDK will probably be much more frequent then changes to the specifications. Keigh had another reason why there are advantages to the current scheme but I forgot what it was.

Splitting the repo will take care of the three issues above.

Will need to figure out how to exactly do the split while keeping the history good. Will need to think about how the SDK refers to the specs (which we may need to do anyway, not sure how this works right now).

**Comment by keighrim** [comment]
> because updates to the SDK will probably be much more frequent then changes to the specifications. 

That was the main reason we decided to only partially synchronize `spec` and `py` version according to #12 and #14. 

---
Separating `mmif-python` while keeping the history intact is the relatively easy part using a proper tool (such as https://github.com/newren/git-filter-repo). And as long as spec files are hosted on github, we can always refer spec files via github urls, so that shouldn't be a impossible challenge either.

**Comment by keighrim** [comment]
I created a new repo at https://github.com/clamsproject/mmif-python and used git filter-repo to see how easily separable this repo is. 
(`git-filter-repo --path LICENSE --path .github --path mmif-python/ --path-rename mmif-python/:`) 
filter-repo went quick and easy, and the resulting repo looks good, except for the bulid piplines (`Makefile` and `.github/`) do not work because of changes of locations of  resource files.

**Comment by keighrim** [comment]
While I was creating a repo for this, I thought we can now format git tags without prefixes (`spec-`, `py-`). Keeping those prefixes seems to be not only redundant, but also inconsistent with [tag format of `clams-python`](https://github.com/clamsproject/clams-python/tags) repo. Let me know how you think.

**Comment by marcverhagen** [comment]
I am up for that. I often used version numbers like "v1.0.7" and I think there may have been a reason for that, but whatever it was, it does not seem to hold anymore.

**Comment by keighrim** [comment]
As of now, I think the separation process on the other side (https://github.com/clamsproject/mmif-python) is done except for two working branches ([23](https://github.com/clamsproject/mmif/tree/23-annotation-subclassing-pregeneration) and [64](https://github.com/clamsproject/mmif/tree/64-vocabulary) ). 
Here's what I did 

1. used [`git-filter-repo`](https://github.com/newren/git-filter-repo) to rewrite the history leaving only commits related to former `mmif-python` directory.
1. all existing `py-x.y.z` tags are renamed to just `x.y.z`
1. all existing `spec-x.y.z` tags are re-tagged with just `x.y.z` 
1. modified `Makefile`, `setup.py` to use the new tag format 
1. modified `Makefile`, `setup.py` to use specification files on github server (not local files) when required 
1. updated the testsuite to use example MMIF file on github server 
    1. this results in failures in tests because there are errors in the everything example file on `0.2.1` commit, which are fixed in `develop` (and probably in `master` too)
1. pushed new main branch and all `x.y.z` tags to the new repo
1. created dummy issues linking to here 

What needs to be done on this side from now on are, 

1. deleting `mmif-python` directory and `py-x.y.z` tags
1. fixing or adding links to [`mmif-python` documentation](https://clams.ai/mmif-python/) in the github.io website
1. publishing a new version with fixes of the errors in the example MMIF

**Comment by keighrim** [comment]
So I pushed a branch with all files related to the python code removed. Now that python development will be done in a separate repository, I think we should merge `spec-0.2.2` into `develop`, and use `develop` for future development of the MMIF specifications. I'll first merge this 112 branch to `develop`.

**Comment by marcverhagen** [comment]
Agreed. We can then revert to the more traditional approach of just creating a release/version branch when preparing it or when it is an issue.

**Comment by keighrim** [comment]
Moved `64` branch to mmif-python repo and clean all working branches. I guess we're ready to release 0.2.2 with that typo (mentioned in today's meeting) fixed.

**Comment by keighrim** [comment]
The last checkbox will be checked via #146, so would this issue be.
