### ISSUE TITLE
Unit conflicts

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#113]
At some point we thought we may have to clean up how we do anchors. Here is one reason why we should. The *BoundingBox* type has a *unit* metadata property which can be used to select pixels for the coordinates. But bounding boxes can also have a *timePoint* property and the unit for that is definitely not pixels.

**Comment by marcverhagen** [comment]
One option would be to use

```json
{
  "contains": {
    "http://mmif.clams.ai/0.2.1/vocabulary/BoundingBox": { 
      "units": { 
        "coordinates": "pixels",
        "timePoint": "milliseconds" }}
    }
}
```

This would be a precedent though in that it would be the first dictionary object that we allow in metadata properties.

**Comment by angus-lherrou** [comment]
It would not be the first.
<img width="990" alt="Screen Shot 2020-10-02 at 2 03 52 PM" src="https://user-images.githubusercontent.com/55718851/94955130-1ce20480-04b8-11eb-8e74-9c25fe66413c.png">

**Comment by marcverhagen** [comment]
Yes and no.

There is precedent when it comes to properties in general: `text` and `coordinates` are two examples, but none of them is a metadata property. Having said that, having those objects on regular properties definitely makes this more palatable for metadata properties.

**Comment by marcverhagen** [comment]
Probably not an issue, at least for now, since:

1. When anchoring to a character stream (_start_ and _end_) the unit is always character offsets.
2. When anchoring to an image (_coordinates_) the unit is always pixels. There are exceptions where locations are referred to by distance from some point, but we do not need to deal with these anytime soon. If we do, we could either convert before putting things into MMIF or add a special property.

So the unit is implied in the cases above and we can use the _unit_ property for the third case: anchoring to a time line.

**Comment by keighrim** [comment]
Maybe we could consider renaming `unit` to `timeunit` and that would solve most of confusion for now without changing anything else.

**Comment by marcverhagen** [comment]
Not a bad idea, and then use `coordinateunit` in case we need it. Maybe use `timeUnit` and `coordinateUnit` for readability.

**Comment by keighrim** [comment]
We can also use something like `charUnit` for text *span*s to indicate the unit for counting unicode characters (assuming all MMIF/CLAMS documents are unicode-based). For instance, python will count unicode characters based on the number of codepoints, but java applications will do with number of codeunits.

**Comment by marcverhagen** [comment]
Just some freewheeling on unit names. If we have `timeUnit` we could have `spaceUnit` for the coordinates (although `coordinateUnit` has perhaps a better ring to it. And `charUnit` is somewhat weird, it is like saying `secondsUnit` (who knows, maybe Java counts seconds differently from Python). Maybe we can have `spanUnit`.

I feel that with `spanUnit=unicodeCharacter` and an encoding we should have enough. Maybe let the apps take care of having the right calculations.

And what units can we really think off? Maybe we should start there before we worry too much about the names. The only current problem that we have is with bounding boxes.

**Comment by keighrim** [comment]
Hmm. I don't think "character unit" is equivalent "seconds unit", as in unicode there are actually various ways to count *characters* (whatever that means) and that is the issue here. But I like what you suggested, namely we just specify that 
1. the unit of text spans is always unicode codepoint
2. TextDocuments in MMIF must be unicode text 
3. When written to a file, MMIF must be encoded in UTF-8

in the MMIF specification and let apps take care of correct character counts (e.g. in java use `string.codePoints().count()` instead of simply `string.length()`). 
However, this will only work for new apps so we will have deal with existing LAPPS services, if we ever try to integrate them into the CLAMS.

**Comment by keighrim** [comment]
This could only be marginally related to this issue, but we have, from #96, 

> - The value of `Polygon>timePoint` is an ID, but we are using it as an integer that reflects a frame number or time measure.

I think the above proposal makes lots of sense. In addition to that, I'd like to also propose renaming `Timepoint::point` ==> `Timepoint::timePoint` for consistency with `Polygon::timePoint`.

**Comment by keighrim** [comment]
fc9487f implements the above comment. Let me know how you think.

**Comment by keighrim** [comment]
Closed via https://github.com/clamsproject/mmif/pull/169.
