### ISSUE TITLE
view metadata

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#117]
In `mmif.serialize.view.View` there is code to add `gen_time` as a property in the contains dictionary for an attype (this also happens in the `Contain` class). 

Typically we only put things in that directory that are defined in the metadata for the attype. Also, having a generation time for an attype seems somewhat redundant given that we have the `timestamp` property on the view metadata.

I vote to remove `gen_time` if it does not serve other needs.

**Comment by keighrim** [comment]
Yeah, that sounds right. I think `gen_time` was a property I throw in almost arbitrarily when I was doing the prototype. I agree for removing it.

**Comment by marcverhagen** [comment]
Fixed in https://github.com/clamsproject/mmif/commit/063bb0360218e5e685ae1a7fc841107d432479ad.
