### ISSUE TITLE
Py 0.2.1

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#124]
We've had a few bugfixes since the release of mmif-python 0.2.0, and we should start thinking about when we want to release them as a new patch version to PyPI

**Comment by keighrim** [comment]
`py-0.2.1` was tagged when #130 was merged and the artifact was published at https://pypi.org/manage/project/mmif-python/release/0.2.1/. Strangely it wasn't merged to `master` branch.
