### ISSUE TITLE
add method to get a specific type of document to `Mmif` class

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#126]
Currently `Mmif` class is missing a method to get a specific type of `Document`s from its `documents` list. Users have to directly access the list and filter the elements. Add `get_documents_type_of(doctype) -> List[Document]` method.

**Comment by marcverhagen** [comment]
Maybe better to call it `get_documents_by_type` since there are already a bunch of methods named `get_documents_by_X`.

**Comment by keighrim** [comment]
closed via #128
