### ISSUE TITLE
add method to get the text from a document

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#127]
A method `get_text()` on `model.Document` that retrieves the text from the document, either from the `text` property or by reading it from the path in the `location` property, the latter might best be done by asking the `clams-python` package to do it, but I do not have strong feelings on that at the moment.

**Comment by keighrim** [comment]
We talked about similar helper methods for `VideoDocument` yesterday. Considering consistency across different document types, I vote for having all helper methods to directly handling files and file systems in `clams-python`, leaving `mmif-python` purely JSON(-LD)-related library. But until we have that set of file handling module in the `clams-python`, I believe having `get_text` just for `TextDocument`s in `mmif-python` would greatly help app developers.

**Comment by keighrim** [comment]
Issue closed in favor of https://github.com/clamsproject/mmif-python/issues/127.
