### ISSUE TITLE
Context indignities

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#13]
This is a gathering space for all issues related to the context. See this [gist](https://gist.github.com/marcverhagen/bba0158178abf0a3547b48550df30924) for an early draft of the context.

Issues:

- [ ] The context expands `id` to `http://mmif.clams.ai/vocab/Annotation#id`, but that means that the identifier for media and views gets the same treatment, maybe expand to something like `http://mmif.clams.ai/vocab/mmif#id`.

**Comment by marcverhagen** [comment]
We now have the context split into two parts:
- One that has scope over the entire MMIF document and that defines keys like *views*,  *text* and *metadata.
- One that has scope over a view and that is there to deal with elements from the vocabulary. Each view has its own context.

This seems to have simplified things a lot, but it does not solve the issue with the identifier. We decided to resolve `id` to `http://mmif.clams.ai/0.1.0/ocab/mmif/id` and not to the property on `Annotation`.

**Comment by marcverhagen** [comment]
It looks like having a simple context for the whole file and two or more contexts for views works as long as the views also have some minimal allowances for non-vocabulary items. The context with scope over the whole files has just the following (which could be put inline):

```json
{
    "@context" : {
        "@vocab" : "http://mmif.clams.ai/0.1.0/vocab/mmif"
    }
}
```

So all terms like *views* and *metadata* will be expanded to full MMIF URIs.

Then for a context for a view, which is geared towards dealing with a vocabulary, we have the following (this is just a fragment):

```json
{
    "@context" : {
        "@vocab" : "http://mmif.clams.ai/0.1.0/vocab/",
        "mmif": "http://mmif.clams.ai/0.1.0/vocab/mmif/",
        "id": "mmif:id",
        "metadata": "mmif:metadata",
        "medium": "Annotation#medium",
        "unit": "Region#unit"
    }
}
```

Structural MMIF elements in the view (only *id* and *metadata* are listed above) will still be mapped to the MMIF URI, while all other things are mapped to vocabulary URIs.

**Comment by keighrim** [comment]
Vocabulary items are defined in the yaml file and published as HTML documents (plus, possibly some other machine friendly formats; #27), but currently we are lacking an equivalent mechanism for concepts we use under `mmif` context. Should there also be another yaml file and webpages for [these concepts](https://github.com/clamsproject/mmif/blob/4dc2e12/context/vocab-clams.json#L8-L15) as well?

**Comment by marcverhagen** [comment]
I was just about to say that we used discriminators in LAPPS for that, but we actually never dealt with LIF terms like `view`. I think we are good for now because we do have the URIs, but having actual definitions would be nice yet low priority.

**Comment by keighrim** [comment]
We no longer use context, so this seems irrelevant now. Closing the issue.
