### ISSUE TITLE
Weird issue with DeepDiff in MmifObject.__eq__

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#131]
Ran into this when testing the Kaldi wrapper.

I had two Mmif objects that were identical except for the timestamps in their views, but the DeepDiff call returns the following:

```python
>>> DeepDiff(first_mmif_obj, second_mmif_obj, ignore_order=True, report_repetition=True, exclude_types=[datetime])
{
    'iterable_item_added': {
        'root.views[0]': <mmif.serialize.view.View object at 0x7fe9b9fa9c50>,
        'root.views[1]': <mmif.serialize.view.View object at 0x7fe9baf6b2b0>,
        'root.views[2]': <mmif.serialize.view.View object at 0x7fe9c8389908>
    }, 
    'iterable_item_removed': {
        'root.views[0]': <mmif.serialize.view.View object at 0x7fe9b260c7b8>,
        'root.views[1]': <mmif.serialize.view.View object at 0x7fe9b260c898>,
        'root.views[2]': <mmif.serialize.view.View object at 0x7fe9b1cbf5c0>
    }
}
```

However, running DeepDiff on the respective View objects returns no difference:

```python
>>> DeepDiff(first_mmif_obj['v_0'], second_mmif_obj['v_0'], ignore_order=True, report_repetition=True, exclude_types=[datetime])
{}  # likewise for the other two views
```

We get the correct result with the following call:

```python
>>> DeepDiff(first_mmif_obj, second_mmif_obj, ignore_order=False, exclude_types=[datetime])
{}
```

When it knows how to pair the View objects, it does fine, but when it has to compare all pairs itself, it is unable to determine that the matching Views are equal.

There are a lot of pair comparison thresholds for diffs ignoring order that we can tweak in the DeepDiff call. For reference, with `get_deep_distance=True`, it reports `'deep_distance': 2.435467363287649e-05`.

**Comment by keighrim** [comment]
Looking at [the current schema](https://github.com/clamsproject/mmif/blob/spec-0.2.1/schema/mmif.json), we have three ordered objects (`array`), namely `documents`, `views` and `view:: annotations`. And currently implementation of those objects are relying on the implementation of `DataList` class, which internally [keeps the elements in a `dict` object](https://tools.ietf.org/html/rfc7159). What happens if we replace the internal data structure to an ordered object (`OrderedDict` maybe?)? 

I think after all, it is important to keep the order of those list-like objects, not only because that is how JSON arrays are supposed to behave ([*An array is an ordered sequence of zero or more values.*](https://tools.ietf.org/html/rfc7159)) but also because we have some operations designed under assumption that they are ordered list (e.g. `alignment` annotations are sorted by the *start* values).

**Comment by marcverhagen** [comment]
Hmmm, good point, we do want to keep the order (although sometimes I think it might be good hygiene for us to have the order be irrelevant). 

As an aside, JSON arrays are ordered yes, but JSON-LD arrays are unordered by default(something that still strikes me as a really really weird decision).

**Comment by angus-lherrou** [comment]
So this raises the question of whether we want order in those lists to matter for equality between two MMIF files.

If we do, I *think* we can just get rid of `ignore_order` in the DeepDiff call. That might cause problems for things that really are unordered, like regular JSON objects, though, so we'd need to do some testing on that front before making that call.

The CPython dict implementation preserves insertion order, so I don't think we need to switch to `OrderedDict`--but it would be pretty easy to make that switch if we decide we want to.

**Comment by keighrim** [comment]
Ah, I must have misread the original question raised. And yes, I think we should specify (somewhere in the spec) those objects as *ordered* and when diffing, we need to take the order into the consideration.

**Comment by angus-lherrou** [comment]
Cool, I'll implement and write some tests for that this week

**Comment by keighrim** [comment]
In MMIF object we only have three *list* type objects: `documents`, `views`, and `annotations` (in a view). In CLAMS vocab, there are some types that use lists as their type (`targets`: list of IDs, `coordinates`: list of point pairs) and there could be more in the future. However vocabulary types are not subclasses of `MmifObject` so they are out of scope of this issue. for MMIF itself, I think there's only a small chance of adding list type objects that aren't ordered at this moment (other than three mentioned above). So I'm biting the bullet and remove that `ignore_order=True` condition from the `__eq__` method.

**Comment by keighrim** [comment]
closed via https://github.com/clamsproject/mmif-python/pull/166.
