### ISSUE TITLE
add a place to hold errors in `viewMetadata`

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#164]
From the discussion at https://github.com/clamsproject/clams-python/issues/36, we'd like to have a place in the `viewMetadata` to record any error occurred during annotation process. For now the `viewMetadata` requires `app` and `contains` at the minimum.  With addition of the `error`, there are a few things we need to decide. 
1. Can there be two or more errors? Namely, should the `error` (or `errors`?) field be a list? 
2. Can an app produce `annotations` as well as `error(s)`? Namely, which should be used for `contains` and `error(s)`, `anyOf` or `oneOf` (see [this](https://json-schema.org/understanding-json-schema/reference/combining.html)) ?

**Comment by keighrim** [comment]
On the first point, I think an app will almost always terminate immediately when there's an error. Thus I don't see a lot of gains to make `errors` as plural and add another layer (list) of complexity. But I admit that having it as a list seems to be more future-proof. 

On the second question, we should restrict apps to produce either annotations or errors in my opinion. Having such a flexibility, first, doesn't make a lot of sense (unless we allow devs to use `error(s)` field to store warning-level messages), and furthermore, will add lots of complexities to downstream MMIF consumers.

**Comment by marcverhagen** [comment]
I agree on both: one error is enough and a component that produces both errors and annotations is weird. In the future we could entertain the thought of logging warnings, but we would have to do that in the MMIF representation.

**Comment by keighrim** [comment]
Closed via #165.
