### ISSUE TITLE
Annotation medium metadata property

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#17]
Maybe remove this now that the `medium` property has been moved out of `contains`, together with other properties that are not there anymore, like `tool`.

**Comment by keighrim** [comment]
I can't remember what this issue was for.. But, with current spec (`0.1.0`), `annotation` property map does not have `medium` related metadata, so I think the above was *implemented* already?

**Comment by keighrim** [comment]
This issue is outdated and no longer getting comments / discussion. Closing this.
