### ISSUE TITLE
"everything" example is not linked anywhere in the spec

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#171]
https://github.com/clamsproject/mmif/blob/master/specifications/samples/everything/index.md is written back in last September but it seems that that example were never actually linked in the main specification document. That md file and associated `raw.json` file also need to be updated to use the python templating (7dc1394b76e67713369b9160460202b47b660fbf) for automatic update in the future.

**Comment by marcverhagen** [comment]
Yeah, I know, it has been on my list.

**Comment by keighrim** [comment]
Opened a PR (WIP).

**Comment by keighrim** [comment]
closed via #173.
