### ISSUE TITLE
releasing MMIF and SDK's 1.0.0

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#181]
Related to #14 , we need to decide if or when we release version 1 of our libraries. I think the beginning of the BAM can be a nice forcing fn for that, but open to all inputs.

**Comment by marcverhagen** [comment]
Let's go through the issues for all three repositories and decide what we want to be in version 1.0.0 milestones. I have started this for the mmif repository, arbitrarily aiming for the end of this year.

One thing to take into account is whether we allow any breaking changes. I think not given what we promised GBH so what we use for version one would be current minor versions with additions and non-breaking patches. Alternatively, we could continue to work for the current project in versions 0.4.1 (mmif), 0.4.6 (mmif-python) and 0.5.1 (clams-python), I don't like the sound of that but could be convinced.

**Comment by keighrim** [comment]
Now MMIF/`mmif-python` 0.5.x, and `clams-python` 0.6.0 are released, and they resolved most of the issues we aimed to resolve for 1.0.0 release. I guess we will do more bug spotting and squashing while updating existing apps for the new SDK. Then, at the end of that process, whatever the last patches added to `mmif-python` 0.5.x and `clams-python` 0.6.x, I think they'll probably be the candidate for 1.0.0.

**Comment by keighrim** [comment]
Done via 

* https://github.com/clamsproject/mmif/pull/200
* https://github.com/clamsproject/mmif/pull/201
* https://github.com/clamsproject/mmif-python/pull/219
* https://github.com/clamsproject/mmif-python/pull/220
* https://github.com/clamsproject/clams-python/pull/151
* https://github.com/clamsproject/clams-python/pull/152
