### ISSUE TITLE
Avoid overwriting existing specifications

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#183]
Adjust the build script so it does not write existing versions in the docs directory. This should only apply to already committed versions.

**Comment by marcverhagen** [comment]
The way I had planned to do this was by checking the local `docs` directory (and using `git ls-files`), that way we do not depend on internet connectivity.

**Comment by keighrim** [comment]
That'd be an easy change. I thought checking the remote repo directly would benefit from the fact that we can safely discard previous local "build" residue that's not been pushed yet. We can also check for local git tags. That won't require an internet connection and will check if a versioned directory is simply an intermittent residue or a previously committed version.

**Comment by marcverhagen** [comment]
Yes, it could be a fallback. And it is indeed possible for me to have locally committed versions that are not pushed, but it is not my typical workflow (that is, I only commit the versioned specs just before I push).

**Comment by marcverhagen** [comment]
What you did is better than what I would have done. I will probably not add it to 0.4.1 and instead have it in 0.4.2 or 1.0.0.
