### ISSUE TITLE
MMIF without access to source files. Is it a problem? 

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#209]
Originally brought up by @owencking in a slack DM ;

--- 

> Owen King  16:26
> But if the FPS doesn't appear in the MMIF, then, if we don't have access to the original file, we won't know the FPS, right?
> 
> Keigh Rim  16:37
> And I don't think that is a problem because MMIF is designed to work with the original file.
>
> Owen King 16:49
> How is the MMIF linked to the original file, though?  It's not embedded in the file, since a single MMIF can have more than one document.  And the filename is not a reliable identifier, since MMIF just uses filenames, not unqualified URIs.  So, maybe there is some meta-metadata file or packaging format that says which MMIF goes with with media file(s)?
> 
> Keigh Rim  16:56
> For now, at least in the scope of aabp, the file names are actually reliable identifiers as GUIDs are recorded in the file names. (...)
> Fundamentally, you are right in that, the users of the clams platform have responsibility of creating and maintaining that meta-metadata records (...) 
> I think this conversation does rather fit into a public discussion than a private slack chat. 
>
> (...) 
> 
> Owen King  17:06
> Yes, please move it to GitHub as appropriate!
---

MMIF was designed as a standalone format that doesn't "include" the entire the source data/document/media, just like all other computational annotation formats, and hence I don't think users' losing information after losing access to the source data is a MMIF/CLAMS problem. 

But maybe we should include the entire source data in the MMIF, if there's a justifiable reason. And regardless of the reason, implementation-wise I think we basically have two highest-level options to choose from; 

1. alter the source file by adding MMIF as a "header" information to the original MP4/MP3/WAV files. This implies a possibility of inventing a new video/audio files format that goes beyond MPEG specification to integrate MMIF annotations into a MPEG-based files, as well as losing the "original" original files (even though they'll be embedded in the new MMIF-MP4 files probably as the same byte sequences, from the preservation or portability perspective , they might not be "the same" files.) Or, 
2. keep duplicating the original source file, either after every step in a CLAMS workflow, or at the final step. This will add not only a huge overhead to disk I/O operations under CLAMS workflows, but will also put a fair amount of financial and environmental burden to the CLAMS users (although, storage is probably the cheapest component in hardware composition these days). 

In either case, I don't think they are realistic approaches we can take within the scope of the ongoing collaboration. Let us know what people think, or if there's a third way (or fourth..?).

**Comment by marcverhagen** [comment]
Indeed, any CLAMS processing results will be less valuable when access to the primary source is lost.

I agree with Keigh that this is not strictly a MMIF problem, but a data handling problem. Adding MMIF data to a source file or the source file to a MMIF file are both technically possible, but will add redundancy to any workflow and probably issues on access rights as well. And given the amount of work needed these approaches are probably not worth the effort.

There is possibly another option which is to do something that Mac OSX does for applications, where the application presents itself as a single file, but it really is a directory with all resource needed, for CLAMS those could be the primary sources and the MMIF files. Running CLAMS on such a file/directory would add MMIF files and hence not introduce added redundancy. However, implementing that is also not at all trivial and it would probably not solve all data access problems anyway.

Having said all that, it would probably still be a good idea to keep data handling protocols at least on the back burner. Personally, I like the approach that Keigh was planning for MMIF, with code handles to deal with various protocols.

**Comment by keighrim** [comment]
No additional input is give, closing the issue as wont-fix.
