### ISSUE TITLE
Assorted fixes in mmif-python

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#21]
- Pathing to `VERSION` file in `publish.py` is broken or inconsistent
- Circular import issue in `mmif.__init__`
- `clams.vocabulary.yaml` should be copied into package resources
- serialize.View needs reworking

**Comment by angus-lherrou** [comment]
Using this to justify a branch that I used to stage my two prototypes for Annotation subclassing

**Comment by keighrim** [comment]
done via #22.
