### ISSUE TITLE
Annotation subclassing prototypes

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#23]
I've made two prototypes for Annotation subclassing: one that pregenerates the subclasses in setup.py, and one that generates them on-the-fly at runtime.

So far the prototypes do not have support for custom annotation types or LIF types. That is next on the agenda for this issue.

**Comment by angus-lherrou** [comment]
Prototype 1: [23-annotation-subclassing-pregeneration](/clamsproject/mmif/tree/23-annotation-subclassing-pregeneration)
Prototype 2: [23-annotation-subclassing-on-the-fly](/clamsproject/mmif/tree/23-annotation-subclassing-on-the-fly)

**Comment by keighrim** [comment]
I vote for pre-generation. It would be easier to read the code (even on github) and debug, if necessary.

Also, I suggest we put auto-generated annotation classes (from vocab definition file) into `vocab` sub-package along with some simple string enums, instead of inside `serialize`. How does everyone think?

**Comment by angus-lherrou** [comment]
Putting them in the `vocab` package is interesting because I'd be worried about cross-importing too much. But if that doesn't bother anyone else, that would make sense. After all, the actual (de)serialization methods would still be on `serialize.Annotation`.

**Comment by keighrim** [comment]
Talked to @marcverhagen yesterday and briefly touched upon this issue. He also seemed to be fond of having pre-compiled python classes. Unless I hear something else, I'll create a PR based on the precompilation branch, so that we can continue develop on the PR.

**Comment by angus-lherrou** [comment]
Sounds good to me. If you want to merge in your typing branches first, I can refactor my changes here to match.

**Comment by keighrim** [comment]
okay, I'm gonna merge #29 and #28 .

**Comment by angus-lherrou** [comment]
I'm tempted to modify my plan for this, for a couple reasons.

1. the project structure gets a bit weird when putting subclasses in vocab and then trying to find a way to initialize an Annotation object as a subclass
2. we already have the field "at_type" for the Annotation class, and my original purpose for having subclasses was to have a way to verify that required properties are present when deserializing existing MMIF files or serializing new ones. I think there's probably a better way of doing that without subclassing Annotation that will also allow end users to add new types for similar verification on data for their projects in a transparent way.

So with that being said I'd like to abandon the subclassing idea and focus on coming up with another way of pregenerating the required property constraints on build, such as just unrolling the type hierarchy as we've been doing and making a prebaked dictionary with all the inherited required properties.

**Comment by keighrim** [comment]
For September deadline, we'll use simple string-based approach (discussed in #64), putting this off for the future.

**Comment by keighrim** [comment]
Issue closed in favor of https://github.com/clamsproject/mmif-python/issues/23.
