### ISSUE TITLE
Publishing vocabulary in additional formats

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#27]
On Wednesday we briefly discussed adding a feature to allow users to use RDF or OWL formats with MMIF. I don't remember exactly how we wanted to support those formats (defining annotation vocabulary? converting to/from JSON-LD? both?), so I wanted to open an issue to discuss that.

**Comment by keighrim** [comment]
The goal is to generate JSON, OWL and TTL formats based off of the YAML file when we "make" the vocabulary. I think the current version only generate HTML version, right? Those auto generated machine readable files, then, are hyper-linked in the HTML page . See [lappsgrid vocab](http://vocab.lappsgrid.org/ ) website for what we did in the past.

**Comment by angus-lherrou** [comment]
Changes in the new branch for this issue are WIP, please ignore. Just setting up tracking for organizational purposes.

**Comment by marcverhagen** [comment]
>  I think the current version only generate HTML version, right? 

Correct. Adding JSON would be very easy and I can do that. OWL and RDF will take a bit more work and I think Angus was volunteered for that.

**Comment by keighrim** [comment]
closing via #39.
