### ISSUE TITLE
experiment with pydantic integration

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#31]
[pydantic](https://github.com/samuelcolvin/pydantic/) is a popular library that supports mappings between python objects and json schema fields, as well as validation and auto generation of schema from python classes. I'd like to experiment with the library to see if it can be utilized for testing and CI pipelines.

**Comment by angus-lherrou** [comment]
This looks promising. We might need to wrap it in something because I'm not sure how to support JSON-LD's @ tags.

**Comment by keighrim** [comment]
8dc75a6c9aea0cbfcab0b7ec38ffc5c2b5942b81 is my attempt to implement a generalized solution for `@` prefix from LD vocabulary. Basically, all `@`- fields are stored as `_`- in compliance to python naming rules. De-/serialization methods will convert between when they are called.

**Comment by keighrim** [comment]
Issue closed in favor of https://github.com/clamsproject/mmif-python/issues/31.
