### ISSUE TITLE
Version 0.1.0

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#37]
I would like to publish and release a first version as soon as possible so that we actually have a full specification out there with vocabulary, schema and context files. Part of the motivation here is so that GBH people can actually see the documents that are part of the specifications.

This requires us to merge into the master branch.

Any reasons not to do this?

An alternative would be some process for pushing files to some development website, but that sounds like extra work.

**Comment by keighrim** [comment]
I have no opposition to this. 

Just so you know, I created & pushed `0.1.1` a few commit later than 0.1.0 while testing my script, and the particular commit that 0.1.1 was laid on was not so carefully chosen and kind of in the middle of develop branch, so we might want to ignore 0.1.1 from publication, though.

**Comment by marcverhagen** [comment]
We have a 0.1.1 commit? Where?

**Comment by keighrim** [comment]
Ah, It looks like I created tags only locally and didn't push to the repo. In such a case, I think we need to discuss which commit to be `0.1.0` (officially). Also, at the moment as we don't have fully functional "builder" we might need get some hands dirty to aggregate all relevant files in the `docs` directory.

**Comment by marcverhagen** [comment]
Okay, I will start a branch named version-0.1.0 and do the legwork for getting a first version out there. Some of it perhaps still manual while not all builder scripts are there. When merged into the master branch I will create a 0.1.0 tag and release.

**Comment by marcverhagen** [comment]
Some things to do:

- [ ] Update specifications to reflect we are not punting on the versions anymore
- [ ] Clean up the specifications and get rid of some stuff like the LAPPS-CLAMS integration
- [ ] Update vocabulary publication script so it also copies the schema and contexts
- [ ] Update vocabulary publication script so it also copies the specifications
- [ ] Merge 37-version-0.1.0 branch into develop branch and master branch

**Comment by angus-lherrou** [comment]
When you refer to intercepting the vocabulary urls on GitHub, do you mean through GitHub Pages? GH Pages doesn't natively support URL rewriting but we could make each page (e.g. http://mmif.clams.ai/0.1.0/vocabulary/TimeFrame.html) into an index.html in a subfolder (so http://mmif.clams.ai/0.1.0/vocabulary/TimeFrame/index.html, which http://mmif.clams.ai/0.1.0/vocabulary/TimeFrame would automatically be redirected to)

**Comment by marcverhagen** [comment]
Yes, Github pages, but I figured it would not allow us to do that. I think I may like your solution a little bit better then my plan which was to add .html to all the terms in the context.

**Comment by angus-lherrou** [comment]
Alright, I've amended publish.py to do what I proposed. Should I push to the 37-version-0.1.0 branch?

**Comment by marcverhagen** [comment]
Yes, I am making changes to the same file but I will merge them.

**Comment by marcverhagen** [comment]
The styles are not working on https://mmif.clams.ai/0.1.0/.

<img width="954" alt="Screen Shot 2020-07-23 at 7 53 34 AM" src="https://user-images.githubusercontent.com/4247673/88283615-bff8ef80-ccb9-11ea-8da9-1de451341744.png">

**Comment by keighrim** [comment]
hmm.. I think I fixed it via a44202305a0d86c144780120afe6ca31418854fc. Could you try no-cache refreshing (shift+cmd+r), or opening it in a spy mode?

**Comment by keighrim** [comment]
next, upload to pypi.

**Comment by angus-lherrou** [comment]
I'm also having issues with that page. Looks like it's an SSL issue: the certs are only valid for GitHub domains, not for clams.ai.

<img width="784" alt="Screen Shot 2020-07-23 at 12 11 45 PM" src="https://user-images.githubusercontent.com/55718851/88310457-aff30700-ccdd-11ea-9819-7202ae8910e1.png">
<img width="1680" alt="Screen Shot 2020-07-23 at 12 10 43 PM" src="https://user-images.githubusercontent.com/55718851/88310387-9a7ddd00-ccdd-11ea-8620-c7fc0756e5da.png">

**Comment by angus-lherrou** [comment]
The same is true for www.clams.ai for me.

The vocabulary pages work fine--they use their own CSS so that's not too surprising.

**Comment by angus-lherrou** [comment]
Interestingly, it works fine on Windows (same browser version)

**Comment by keighrim** [comment]
I think I found a solution, working on it.

**Comment by keighrim** [comment]
It looks fine now on linux, mac, and windows both with FF and GC. Can anyone else confirm?

**Comment by angus-lherrou** [comment]
Confirmed!

**Comment by keighrim** [comment]
Two tags are pushed https://github.com/clamsproject/mmif/releases and bulid from `py-0.1.0` is pushed to pypi (https://pypi.org/project/mmif-python/#files). All set for 0.1.0 for now.
