### ISSUE TITLE
python-sdk bulider 

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#42]
as a subtask of #19 , I'd like to add a builder script to the sdk. 
Here's what the parent issue outlined for sdk bulider 

--- 
* sdk builder (currently mmif-python)
  * make publish - when there's an update in sdk codebase, version it, package it (setup.py), publish to pypi
  * make dev - package sdk and install to local development environment (maybe upload to the lab pypi too?)

**Comment by angus-lherrou** [comment]
@keighrim would it be possible for us to work together on this? I'm unfamiliar with publishing packages to pypi and it would be good to get the experience in understanding that process.

**Comment by keighrim** [comment]
Yeah, sure, sounds good to me. I'm now detailing specifics of processes and necessary commands for the *making*, so let  me share it once it's ready and then we can divide work.

**Comment by keighrim** [comment]
Least necessary steps needed for each verb; 
#### make publish
1. asks for a new version
1. create `VERSION` file (or an equivalent mechanism) and generate `ver` subpackage
1. checkout latest schema and vocab files using git tags 
1. generate `res` sub package using external files 
1. (future) generate `Annotation` subclasses from vocab 
1. run pytype and pytest and see if all pass
1. build for [sdist and bdist](https://python-packaging-tutorial.readthedocs.io/en/latest/uploading_pypi.html#source-distribution)
1. `twine-upload` to pypi.org

#### make dev 
1. check for [`devN`](https://www.python.org/dev/peps/pep-0440/#development-release-separators) version from llc pypi
    1. if none exist, create a new one by bumping up latest version (e.g. `x.y.z` -> `x.y.z+1.dev1`)
1. use schema and vocab from `HEAD` and do above (code generation, testing)
1. do not build for s/bdist but run setup.py in [development mode](https://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode)
1. `twine-upload` to lab pypi

**Comment by keighrim** [comment]
Maybe build and upload should happen once all commits are merged to `master`... If so, build and upload would be part of the build in root, not of sdk builder

**Comment by keighrim** [comment]
Closing via #58
