### ISSUE TITLE
git tagging with version

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#44]
As now we are just about to *release* first alpha version (`0.1.0`), I wonder which tagging scheme we should use for tagging the release in git. Note that we have two different versions (spec version and python sdk version) that are only partially synchronized. So, we can use base, unspecified `x.y.z` scheme for spec version (as if the spec is the main dish) and more specified `x.y.ẑ-python` scheme for python sdk. Or we can treat them equally and use specified schemes for both (`x.y.z-spec`, `x.y.ẑ-python`) (Of course we can use shorter suffixes as in `x.y.zs` or `x.y.ẑp`). Any other idea is also welcomed.

**Comment by marcverhagen** [comment]
Since versions cannot start with a number anyway why don't we use `spec-0.1.0` and `sdk-0.1.0` for this very first version (two tags) and then have the two increment independently along the z dimension and synchronize when we update the minor or major version.

**Comment by keighrim** [comment]
> Since versions cannot start with a number 

Not sure what you meant by this, but I think having prefixes is actually better for separating two versions by simply sorting. I'll use `spec-x.y.z` for specification and `py-x.y.z` for python sdk (just in case we extend the sdk to other languages other than python, which is not very likely but just leaving some room).

**Comment by keighrim** [comment]
0.1.0 commits are tagged using schemes discussed above. Closing the issue.

**Comment by marcverhagen** [comment]
That's exactly what I suggested.
