### ISSUE TITLE
mmif-python: Documentation

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#46]
For later: start writing documentation for all exposed objects and methods in the MMIF SDK

**Comment by keighrim** [comment]
Looking at the current working branch (`46-documentation`), I realize that it is quite behind the current develop branch, but contain only few commit. I'd like to suggest we start a new branch from current `develop` and replace `46` with the new one, to avoid merging headache in the future.

**Comment by angus-lherrou** [comment]
Works for me

**Comment by keighrim** [comment]
Initial documentation and sphinx configs are added via #90. Closing this issue for now. Please start a new issue in the future when bugs are found in sphinx pipeline, or specific documentation tasks are required.
