### ISSUE TITLE
Can only deserialize MMIF from str, not dict

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#55]
Because of the current logic regarding `Mmif.validate()` and `MmifObject.deserialize()`, `validate()` expects `@context` (matching the JSON-LD schema) but `deserialize()` expects `@context` for strings and `_context` for dicts. This means that when you try to initialize a Mmif object from a dict, if it has `@`-tags you get a `KeyError` in `Mmif._deserialize()` when extracting `self._context`, but if it has `_`-tags you get a `ValidationError` in `validate()`.

One fix for this is to have `MmifObject.deserialize()` replace `@` with `_` for both dicts and strings, which requires a minor change to `MmifObject._load_str()` (which should probably be renamed at that point).

@keighrim do you see any problems with making such a change?

**Comment by keighrim** [comment]
Now reading [what I wrote the other day](https://github.com/clamsproject/mmif/blob/master/mmif-python/mmif/serialize/model.py#L67-L68), I can't remember why I wrote that... There might have been a plausible reason behind that, but at the moment I can't think of it (probably I should have left more detailed comments there). Having a consistent behavior across different types of input seems to be a better practice anyway, so I'm in for fixing this.

**Comment by angus-lherrou** [comment]
Okay, fixing in #47

**Comment by keighrim** [comment]
also fixed via #57
