### ISSUE TITLE
@context in a view?

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#56]
[This example file](https://github.com/clamsproject/mmif/blob/master/docs/0.1.0/samples/example-1.json) fails validation against the [current schema](https://github.com/clamsproject/mmif/blob/master/docs/0.1.0/schema/mmif.json) due to the presence of an `@context` attribute in a view. Should our schema account for `@context` in a view?

**Comment by keighrim** [comment]
#13 suggests having multiple context at different levels. Unfortunately the schema doesn't seem to be up to date regarding that suggestion.

**Comment by marcverhagen** [comment]
Updated MMIF schema in https://github.com/clamsproject/mmif/commit/a319c18ede01c9bd42c5558e7fe3236a238cbf8f.

**Comment by marcverhagen** [comment]
This did result in a failed codecov run.

**Comment by angus-lherrou** [comment]
Note that the tests currently disabled by the `SKIP_FOR_56` flag will keep failing until the git tag is changed to be at or past a319c18.

They still fail afterwards but that's because of an unrelated bug related to the gen_time attribute of Contain objects. I could have sworn I fixed that already but I must have dreamt it.

**Comment by angus-lherrou** [comment]
I've tracked down the issue with `test_add_property` that caused codecov to fail. Well, first, I had a malformed example file, but fixing that revealed another issue there. It's ultimately related to #64 / #68, where basically the program isn't recognizing that a `TimeFrame` and a `http://mmif.clams.ai/0.1.0/vocabulary/TimeFrame` are the same thing.

@marcverhagen @keighrim I'm not sure whether we want to say that we'll have #64 ready as part of our September deliverable, but if not, we may have to stick a requirement in for the current spec that the keys in a view's "contains" dictionary need to be identical to the `@type`s of annotations in that view, instead of just semantically identical.

**Comment by angus-lherrou** [comment]
I've pushed a hotfix that will work for now (splitting the keys and the `@type`s by '/' and comparing the last element) but let's not rely on it.

**Comment by keighrim** [comment]
is the [branch](https://github.com/clamsproject/mmif/tree/59-alignment) ready for a PR?

**Comment by marcverhagen** [comment]
Yes, as far as I am concerned. But in the open pull request I see that some checks failed.

**Comment by keighrim** [comment]
No worries, those are about losing test coverage.

**Comment by marcverhagen** [comment]
It is not clear to me how the conflicts should be resolved so maybe @angus-lherrou can do the honors.

**Comment by angus-lherrou** [comment]
Sure thing

**Comment by angus-lherrou** [comment]
All set now, if someone else wants to review

**Comment by keighrim** [comment]
closed via #78
