### ISSUE TITLE
Interpretation of contains in view metadata

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#65]
According to the specification, the `contains` dictionary's keys consist of all the annotation types in that view, with the values being the metadata associated with those annotation types, such as units. By this definition, it would seem that all of the annotations of the same type within a view are assumed to have the same metadata--for instance, you couldn't have two Intervals, one with units in seconds and another with units in frames, in the same view.

This seems like a valid restriction, since it seems like semantically one view would encompass at most one way of looking at intervals in an audio clip or what have you, but I wanted to put it in writing here to get confirmation that this is something we want to enforce.

**Comment by keighrim** [comment]
I think the interpretation is correct given our current specification. If an app adds the same type of annotations with different parameters/metadata, I'll say the app is doing something wrong. But, you're right in that we haven't documented such expected behavior in anywhere in the specification.

**Comment by marcverhagen** [comment]
I put some prose on this in commit https://github.com/clamsproject/mmif/commit/f54aa0f831536198944624f527674b951a7f2d83.

**Comment by keighrim** [comment]
closed via #79
