### ISSUE TITLE
`AnnotationProperties.properties` dict doesn't get created when using `View.new_annotation`

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#76]
When creating a new AnnotationProperties object, the `id` field gets set, but the `"id"` key in `properties` does not get set and in fact the `properties` dict is never initialized, leading to issues with serialization.

Fixed by adding `@property` getters and setters to AnnotationProperties and initializing the `properties` dictionary.

**Comment by keighrim** [comment]
closed via #77
