### ISSUE TITLE
Changing the structure of annotation types

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#8]
In LAPPS we had "attype", "id", "start" and "end" (and earlier even "label" and "type") defined directly on the annotation, and then a bunch of properties in the "features" dictionary. 

```json
{
  "@type": "Token",
  "id": "t0",
  "start": 0,
  "end": 5,
  "features": { "word": "}
}
```

This proved confusing to people and it sure was not very consistent. I for one found there was little rhyme or reason to why things were where they were and did not like something being called 'properties' in the vocabulary and 'features' in LIF.

How about we only have "attype" and "properties" and put all properties defined in the vocabulary as well as others in the map. 

```json
{
  "@type": "Token",
  "properties": {
    "id": "t0",
    "start": 0,
    "end": 5,
    "word": "Dingo"
}
```

We may want to make an exception for "id" and put it on the top level since it is required for every annotation.

Possible disadvantage is lower compatibility with LIF.

**Comment by keighrim** [comment]
I would also try to integrate more [JSON-LD keywords](https://json-ld.org/spec/latest/json-ld/#syntax-tokens-and-keywords) into MMIF, for example `id` --> `@id` (that opens a question of converting current `id` format to URI format though).

**Comment by marcverhagen** [comment]
One problem with `@id` is that its value is a URI (well, IRI)  and it needs to have some meaning and I fail to see how the annotation identifiers have that kind of meaning.

**Comment by keighrim** [comment]
Yeah, having all `id` as URIs might not be a good idea, adding a lot of complexity to readability and storage. I'll further explore other possible integration with JSON-LD features though.

**Comment by keighrim** [comment]
implementation is deferred until #26 is done.

**Comment by keighrim** [comment]
After some recent thought, I'm now not sure whether we should push `id` down to the props map. I (somewhat vaguely) remember we discussed on troubles from having two different *meanings* of `id`, between id of a view and id of an annotation. On top of that, it's also confusing to me that other objects (`view`, `medium`, ...) have `id` at the top level of their serialized representation, while only `annotation` has it nested under the `properties` map. 

I would like to suggest, we just remove [`id` from the vocabulary definition](https://github.com/clamsproject/mmif/blob/0a57fa1012ae34aeaff799649212c936e0afaf44/vocabulary/clams.vocabulary.yaml#L16-L21), as `id` appears to be not adding any semantic information to an annotation object. It's required for being referred from an external agent, and can be purely syntactically defined in the json schema.

**Comment by marcverhagen** [comment]
Yeah, that is a point worth considering. Moving `id` to the annotation from the properties map does not help the issue with the two meanings of `id` though. But there is indeed some inconsistency with `view` and `medium`. On the other hand, that is not the only inconsistency: we have many maps without ids (metadata, contains, text, etcetera) and moving `id` up would just change the set of maps with ids. 

Removing `id` from the vocabulary would not be my first thought here. There is something semantic about an annotation being able to be identified as its won entity, even if it is exactly the same as another annotation (rare, but possible) and we do have things like `target` that refer to ids.

It looks like we cannot win here.

**Comment by marcverhagen** [comment]
Another difference between annotations and views and media is that annotations have a `@type` attribute but the others don't.

**Comment by keighrim** [comment]
Implementation is updated via #38 . There's an ongoing issue for optimizing implementation by using python `dict` (#40 ) but that should have nothing to do with serialized structure of `Annotation` object. 

--- 

Media might need their `@type` in the future, but I'll start a new issue on that. We can always revisit the placement of `id` of `Annotation` object, but for now everyone seems to be happy with `id` in `properties`. I'm closing this issue.
