### ISSUE TITLE
usage of files in `specifications/samples`

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#80]
I don't see any reference to any of those files from specification document, or any other component. But I see some of those files are used as test resources for in the `mmif-python`. I'd like to suggest, instead of having duplicates in `spec` directory and `mmif-python/tests` directory, we make`Makefile` to copy these files at test time so that we reduce maintenance cost as well as keep the MMIF *showcase* up to date with the python code.

**Comment by angus-lherrou** [comment]
Some of the examples in mmif_examples.py are modified from the samples in order to target some edge behavior.

This wouldn't be impossible to rework but maybe not for September.

**Comment by keighrim** [comment]
I was looking at `spec-0.2.0` and found that [this commit](https://github.com/clamsproject/mmif/commit/339c74c48d8eaef52b8bfebf929174036b88d83a) added subdirectories in the `specifications/samples` directory. I understand that makes having links to the raw json files inside the md files a bit easier (eliminating changing directory to`../`, and some confusions in turn) , but I prefer having a single directory that holds all the json files to having to recursively look for json files and rename them based on the direct parent directories of theirs, when making use of them for SDK testing in the future. @marcverhagen would you mind I mend those files?

**Comment by marcverhagen** [comment]
Let me think about it. I perhaps did that for a reason having to do with how Jekyll deals with md files that are not named index.md.

Also, if we give ourselves a restriction that all json files have to be in a particular location because we want to easily find them then we have a problem. One alternative would be to have one file that has all the locations of all json files that we want to include in the tests. Also notice that just one path would allow you to find all example json files (`samples/*/raw.json`).

**Comment by keighrim** [comment]
Alright, sounds fair. 

Another thing I noticed was that there are `md` files that duplicate json files in their internal code blocks. That might potentially lead to discrepancy between duplicates, and add maintenance work that could be avoided. 6d46250 is an attempt to remove such possibility by using jekyll `include` filter (it also uniformly convert all JSON indentation to two spaces).

**Comment by marcverhagen** [comment]
Yeah, that duplication did not sit well with me either and I was thinking of just having the link. This is better though.

**Comment by keighrim** [comment]
With #173, all samples are linked to the main spec documentation and all `json` files of samples are readable as uniform python template. Most tests updated and implemented as of clamsproject/mmif-python#177 now based on the *everything* sample, but any other samples are also available for test suite. I think this issue now all resolved. Closing it.
