### ISSUE TITLE
Redesigning the vocabulary and MMIF

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#86]
This was raised in https://github.com/clamsproject/mmif/issues/59, but the issue goes beyond alignment so creating a new issue.

**Comment by marcverhagen** [comment]
@keighrim @angus-lherrou 

There is a write up of our discussion in commit [c6eacf4](https://github.com/clamsproject/mmif/blob/c6eacf4becb6d1046d09340b4d02030bafab1880/specifications/notes/vocabulary-redesign.md). It sort of morphed into a proposal.

**Comment by marcverhagen** [comment]
Better to just go straight to the branch: https://github.com/clamsproject/mmif/blob/86-vocabulary-redesign/specifications/notes/vocabulary-redesign.md.

**Comment by marcverhagen** [comment]
A few remarks on this:

- I think we now all agree on using *document*, I will banish *medium* from the specifications

- There is a *document* property with a list of media/document identifiers. In this case it is not needed because the Token and the TimeFrame could each have their own document metadata property. But if we have two media that time frames could refer to we cannot use a list of documents anyway to resolve what medium to use and we need to check the individual annotations. So the list is not needed.

- For the segments list we have the *by* property for every single element, that does not feel right.

- I don't see why the above proposal makes it really complicated to have a TextDocument inside the annotations list. But if that is the case we need to introduce sub media again and make the media list editable.

- The use cases identified are real, but I think the solution should be in the SDK or user-created software instead of in MMIF. The MMIF file needs to have the information needed, either explicitly or implicitly (that is, it can be calculated from what is explicit). The SDK needs to give you procedures to get to that information, potentially building auxiliary data structures in the process.

To elaborate the last point here are the two use cases:

1. A ML researcher wants to get all annotations at each time frame to generated concatenated vector representation. 

2. A web developer wants to develop a MMIF visualizer with a video player and a transcript reader together side-by-side, and bidirectional synchronization between those two panels. i.e. 1) as video plats, auto-scroll text panel, 2) as reader click on a word in the text, seek to the point in the video player. 

What I imagine is that the SDK could take the MMIF file and build some kind of a graph with annotations rooted in the anchors (the start and end offsets of the annotation) or other annotations. All elements in the graph would be indexed and their would be some extra functionality to do things like finding all annotations at a particular locations (single offset or span), some auxiliary data structure may be needed for this.

Use case 1. Not sure what "each time frame" means, but an SDK that could find annotations at certain time points and timeframes would be helpful. Since each annotation has an anchor or target, the information we are looking for is in the MMIF file even when following the current specifications.

Use case 2. This requires the ability to follow the entity to the token to the alignment to the time frame. Again, that information is in the MMIF file and the SDK could deliver functionality that efficiently gets that information. With the above proposal you indeed need not first trace to the Token and then the alignment and then the segment. But the developer does not need to do that when the SDK does it for you.

This is not to say of course that the current proposal is better than having a list of alignments at the top level linking to segments at the top level. But I think the use cases are not so relevant in picking what we like best. What would make sense thinking about is what kind of information we would like to easily extract using the SDK, but that is more of an issue for SDK design than MMIF design.

What we project to the outside world are MMIF and the SDK API, those need to be as simple as possible, the more complexity we hide in the SDK the better.

**Comment by marcverhagen** [comment]
@keighrim @angus-lherrou  

I am running into a little glitch while working out how to use alignments within views and I think this also extends to the alternative approach of having an alignment list on the top-level. The issue is that when we have different kinds of alignments in a view or an alignment list we cannot just rely on the metadata to tell us what the types of the alignment are.

With Kaldi output we have a text document aligned with a speech segment and a bunch of tokens aligned with a bunch of speech segments. We could have *sourceType* and *targetType* as regular properties as well (which we also need to do for the *document* property) and then overwrite the type for the text document, and something similar could be done with the list of alignments (but that won't be pretty).

An alternative is to entirely ditch the metadata properties, which would simplify things. An alignment is between two annotations and we really do not specify what type they are. Is there any SDK-related reason (or other reason) why we should not abolish the *sourceType* and *targetType* properties?

**Comment by keighrim** [comment]
So Kaldi essentially generates three types of annotations; 1) text itself 2) tokens, and 3) timeframes (at token level). How about we decide to only align the smallest *units* when there are the same kinds of annotations with different *units*. In this case, we only align 2) and 3) (both token level, and both are shortest of their kinds).

**Comment by marcverhagen** [comment]
When we do that we will lose the information that the entire text document is aligned with the entire speech/video stream, which I guess is fine, but potentially somewhat inconsistent with other text documents most of which will align with some speech segment or image region. I would still like us to have a good reason for having those types.

**Comment by keighrim** [comment]
I don't think we lose information about alignment between `textdocument` and `timeframe::speech` segments, simply because it is trivial to reconstruct that linkage by sorting `token`-`timeframe::token` alignment list and traverse it to find matching start and end points. 

Anyway, if we want to keep both alignments, I think we can also make Kaldi to generate two sets of alignments, each of which keeps the `source/targetType` metadata.

**Comment by keighrim** [comment]
The core ideas of the proposal in `59` branch and [my long comment above ](https://github.com/clamsproject/mmif/issues/86#issuecomment-678423189) are
1. separation between *unitization* and *labeling* annotations
1. single places to keep segmentation and alignments for easy sort and merge 

So, keeping that in mind, some of my thoughts on the above remarks; 
> I don't see why the above proposal makes it really complicated to have a TextDocument inside the annotations list. But if that is the case we need to introduce sub media again and make the media list editable.

Because I want a single place to put segmentation lists, I also want all `document` objects in a single list, not scattered over many views. 

> For the segments list we have the by property for every single element, that does not feel right.

I now think that we can purge all metadata related to their origin from `segment` objects. Instead we can keep a list of segment ID's that an app generated in the app's own view. We can also mark an origin of an alignment in the same way. For example, the above example after forced alignment can be something like this; 
(I picked verbs as field names to avoid name conflict, and renamed `annotations` to a verb as well to match the style, but it's just exemplary)

```
{
  "documents": [
    {
      "id": "m1",
      "type": "https://.../VideoDocument",
      "mime": "video/mp4",
      "location": "/var/archive/video-0012.mp4",
      "segments": [
        {
          "id": "s1",
          "@type": "http://mmif.clams.ai/0.1.0/vocabulary/TimeSegment",
          "properties": { "start": "17", "end": "1064" }, # Karen 
        },
        ...
        {
          "id": "s6",
          "@type": "http://mmif.clams.ai/0.1.0/vocabulary/TimeSegment",
          "properties": { "start": "5252", "end": "6123" }, # City
        }
      ]
    },
    {
      "id": "m2",
      "type": "https://.../TextDocument",
      "mime": "text/plain",
      "text": {
        "@value": "Karen flew to New York City.",
        "@language": "en"
      },
      "segments": [
        {
          "id": "s1",
          "@type": "http://mmif.clams.ai/0.1.0/vocabulary/TextSegment",
          "properties": { "start": "0", "end": "5" }, # Karen
        },
        ...
        {
          "id": "s7",
          "@type": "http://mmif.clams.ai/0.1.0/vocabulary/TextSegment",
          "properties": { "start": "27", "end": "28" }, # .
        }
      ]
    }
  ],
  "alignments": [
    {
      "id": "a1", # not sure this many metadata is useful for alignment lists
      "source": "m1",
      "target": "m2",
      "sourceType": "https://.../VideoDocument",
      "targetType": "https://.../TextDocument",
      "aligned": [
        [ "m1:s1", "m2:s1" ],
        [ "m1:s2", "m2:s2" ],
        [ "m1:s3", "m2:s3" ],
        [ "m1:s4", "m2:s4" ],
        [ "m1:s5", "m2:s5" ],
        [ "m1:s6", "m2:s6" ]
      ]
    }
  ],
  "views": [
    {
      "id": "v1",
      "@context": "http://mmif.clams.ai/0.1.0/context/vocab-clams.json",
      "metadata": {
        "timestamp": "2020-05-27T12:23:45",
        "app": "http://tools.clams.ai/gentle-forced-aligner"
      },
      "segmented": ["m1:s1", "m1:s2", ... "m2:s7"]
      "annotated": [] # no *labeling* done in this view
      "aligned": ["a1"]
    }
  ]
}
```

**Comment by marcverhagen** [comment]
> Because I want a single place to put segmentation lists, I also want all document objects in a single list, not scattered over many views.

Ah, I see. That does mean we would need to add structure to the documents list unless we are willing to have potentially very long lists all with text snippets that Tesseract found in all the text boxes as top-level documents.

> I now think that we can purge all metadata related to their origin from segment objects. Instead we can keep a list of segment ID's that an app generated in the app's own view. ...

I think you will have to run me through that example in our CLAMS meeting today. Is it actually implying that alignments are not annotation types anymore? Or is "a1" in the "aligned" list an alignment that is spelled out in the annotations of the view?

**Comment by keighrim** [comment]
With separation of unitization from labeling, I think the proposal #59 introduces four types of annotations; 
1. unitization (represented in `segmentations`) 
1. labeling (represented in `view>annotations`)
1. linking between units (represented in `alignments`) 
1. linking between labels (represented in `view>annotations` as *relation* annotations - subtypes of `@type:GenericRelation`)

I know that, in proposal#59 as drafted currently, places where these different types of annotations live and their representations are awfully inconsistent (and probably quite redundant). I'm hoping to seek improvements, but at the same time I'm also a bit doubtful whether this approach is in a right direction. Maybe I'm just making the problem lot more complicated than it is.

**Comment by marcverhagen** [comment]
> Maybe I'm just making the problem lot more complicated than it is.

Maybe, maybe not. I do think that what you propose makes the representation more complex, what we need to decide is whether it is worth it and whether other approaches may be simpler overall.

What we already agree on is that this would be not for a version 0.2.0. I will try to pencil down the current shape of 0.2.0 before the meeting this afternoon.

**Comment by keighrim** [comment]
As all changes discussed in this thread are specified in `spec-0.2.0`, closing this issue.
