### ISSUE TITLE
update python test suite for py-0.2.0

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#99]
Python code for handling MMIF objects are updated in cabec75, but the test suite we have was written for 0.1.0, and is failing with the updated code. Update test code accordingly.

**Comment by keighrim** [comment]
While #80 is in discussion, one can manually copy and use those files in [specifications/samples](https://github.com/clamsproject/mmif/tree/master/specifications/samples) as a test bed.

**Comment by angus-lherrou** [comment]
Assigning to myself as I've been working on this task

**Comment by keighrim** [comment]
Closed via #107 .
